# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd restapi/
          chmod +x ./rest_api.sh
          ./rest_api.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Set Docker image tag
        id: image_tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
  
      - name: Build and tag Docker image
        run: docker build . --file restapi/Dockerfile --tag yaminiholla09/cais:${{ env.IMAGE_TAG }}
  
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/yaminiholla09/cais:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  
      - name: Push Docker image
        run: |
            docker push yaminiholla09/cais:${{ env.IMAGE_TAG }}   

      - name: Run Terrascan
        id: terrascan
        uses: khulnasoft/terrasec-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan
        
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve 


    
  
  
